/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UserReviewsRouteImport } from './routes/user.reviews'
import { Route as UserRecordsRouteImport } from './routes/user.records'
import { Route as UserFavoritesRouteImport } from './routes/user.favorites'
import { Route as UserBooksRouteImport } from './routes/user.books'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserReviewsRoute = UserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UserRoute,
} as any)
const UserRecordsRoute = UserRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => UserRoute,
} as any)
const UserFavoritesRoute = UserFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => UserRoute,
} as any)
const UserBooksRoute = UserBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/books': typeof UserBooksRoute
  '/user/favorites': typeof UserFavoritesRoute
  '/user/records': typeof UserRecordsRoute
  '/user/reviews': typeof UserReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/books': typeof UserBooksRoute
  '/user/favorites': typeof UserFavoritesRoute
  '/user/records': typeof UserRecordsRoute
  '/user/reviews': typeof UserReviewsRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/books': typeof UserBooksRoute
  '/user/favorites': typeof UserFavoritesRoute
  '/user/records': typeof UserRecordsRoute
  '/user/reviews': typeof UserReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/user'
    | '/admin/books'
    | '/admin/records'
    | '/admin/users'
    | '/user/books'
    | '/user/favorites'
    | '/user/records'
    | '/user/reviews'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/books'
    | '/admin/records'
    | '/admin/users'
    | '/user/books'
    | '/user/favorites'
    | '/user/records'
    | '/user/reviews'
    | '/admin'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/user'
    | '/admin/books'
    | '/admin/records'
    | '/admin/users'
    | '/user/books'
    | '/user/favorites'
    | '/user/records'
    | '/user/reviews'
    | '/admin/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/reviews': {
      id: '/user/reviews'
      path: '/reviews'
      fullPath: '/user/reviews'
      preLoaderRoute: typeof UserReviewsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/records': {
      id: '/user/records'
      path: '/records'
      fullPath: '/user/records'
      preLoaderRoute: typeof UserRecordsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/favorites': {
      id: '/user/favorites'
      path: '/favorites'
      fullPath: '/user/favorites'
      preLoaderRoute: typeof UserFavoritesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/books': {
      id: '/user/books'
      path: '/books'
      fullPath: '/user/books'
      preLoaderRoute: typeof UserBooksRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserBooksRoute: typeof UserBooksRoute
  UserFavoritesRoute: typeof UserFavoritesRoute
  UserRecordsRoute: typeof UserRecordsRoute
  UserReviewsRoute: typeof UserReviewsRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserBooksRoute: UserBooksRoute,
  UserFavoritesRoute: UserFavoritesRoute,
  UserRecordsRoute: UserRecordsRoute,
  UserReviewsRoute: UserReviewsRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
